version: 2.1
jobs:
  build:
    docker:
      - image: cimg/android:2023.10.1
    steps:
      - checkout
      - run:
          name: Make gradlew executable
          command: chmod +x ./gradlew
      - run:
          name: Check Java & Android SDK
          command: |
            java -version
            echo "ANDROID_HOME=$ANDROID_HOME"
            ls $ANDROID_HOME
      - run:
          name: Run Gradle Build
          command: ./gradlew build
      - run:
          name: Run Lint
          command: ./gradlew lint
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports
workflows:
  build-and-test:
    jobs:
      - build
